services:
  postgres:
    image: postgres:15-alpine
    container_name: lattice-db
    environment:
      POSTGRES_USER: lattice
      POSTGRES_PASSWORD: lattice_password
      POSTGRES_DB: lattice
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: lattice-cache
    ports:
      - "6379:6379"

volumes:
  postgres_data:
